version: '3'

services:
  pgdb:
    env_file:
      - ./.env
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${POSTGRES_DATA}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    restart: unless-stopped

volumes:
  data: