services:
  pgdb:
    env_file:
      - ./.env
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${POSTGRES_DATA}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data/
    restart: on-failure
  redis:
    env_file:
      - ./.env
    image: redis:latest
    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    restart: on-failure
    ports:
      - "6379:${REDIS_PORT}"

#  swagger-editor:
#    image: swaggerapi/swagger-editor
#    ports:
#      - 80:8080
#    volumes:
#      - ./swagger.yml:/tmp/swagger.yml
#    environment:
#      - SWAGGER_FILE=/tmp/swagger.yml


volumes:
  db_data:
    driver: local