# Generated by Django 5.0.3 on 2024-05-20 18:57

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
        ("stocks", "0008_alter_stock_options_alter_stockdata_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notifications",
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
            },
        ),
        migrations.AlterModelOptions(
            name="transactions",
            options={
                "verbose_name": "транзакция",
                "verbose_name_plural": "транзакции",
            },
        ),
        migrations.AddField(
            model_name="transactions",
            name="direction",
            field=models.CharField(
                choices=[("B", "buy"), ("S", "sell")],
                default=None,
                verbose_name="направление транзации",
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=3, max_digits=10, verbose_name="цена валюты"
            ),
        ),
        migrations.AlterField(
            model_name="transactions",
            name="volume",
            field=models.PositiveIntegerField(verbose_name="количество акций"),
        ),
        migrations.CreateModel(
            name="PortfolioStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        verbose_name="количество акций в портфеле"
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "акция в портфеле",
                "verbose_name_plural": "акции в портфеле",
            },
        ),
    ]
