# Generated by Django 5.0.3 on 2024-05-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_notifications_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portfoliostock",
            old_name="amount",
            new_name="volume",
        ),
    ]
