# Generated by Django 5.0.3 on 2024-04-26 08:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ticker", models.CharField(max_length=5, unique=True)),
                ("description", models.TextField()),
                ("emitent_country", models.CharField(max_length=50)),
                ("market", models.CharField(max_length=100)),
            ],
        ),
    ]
