# Generated by Django 5.0.3 on 2024-04-26 19:45

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="цена открытия",
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="цена закрытия",
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="самая высокая цена",
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=10,
                        verbose_name="самая низкая цена",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=14,
                        max_digits=25,
                        verbose_name="объем торгов(в деньгах)",
                    ),
                ),
                (
                    "volume",
                    models.IntegerField(verbose_name="объем торгов(в акциях)"),
                ),
                ("begin", models.DateTimeField(verbose_name="время открытия")),
                ("end", models.DateTimeField(verbose_name="время закрытия")),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stocks.stock",
                    ),
                ),
            ],
        ),
    ]
