# Generated by Django 5.0.3 on 2024-04-26 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_stockdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="close",
            new_name="close_cost",
        ),
        migrations.RenameField(
            model_name="stockdata",
            old_name="open",
            new_name="open_cost",
        ),
    ]
