# Generated by Django 5.0.3 on 2024-05-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_alter_stock_ticker"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="stock_id",
            new_name="stock",
        ),
    ]
