# Generated by Django 5.0.3 on 2024-05-23 20:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_rename_stock_id_stockdata_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
