# Generated by Django 5.0.3 on 2024-05-18 16:42

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_alter_stockdata_volume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="stock_id",
            new_name="stock",
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
