# Generated by Django 5.0.3 on 2024-05-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_alter_stockdata_volume"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockdata",
            old_name="stock_id",
            new_name="stock",
        ),
    ]
