# Generated by Django 5.0.3 on 2024-05-18 17:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0006_rename_stock_id_stockdata_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="volume",
            field=models.PositiveBigIntegerField(
                verbose_name="объем торгов(в акциях)"
            ),
        ),
    ]
