# Generated by Django 5.0.3 on 2024-05-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_alter_stockdata_volume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stock",
            options={"verbose_name": "акция", "verbose_name_plural": "акции"},
        ),
        migrations.AlterModelOptions(
            name="stockdata",
            options={"verbose_name": "свеча", "verbose_name_plural": "свечи"},
        ),
    ]
