# Generated by Django 5.0.3 on 2024-05-21 13:07

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0008_alter_stock_options_alter_stockdata_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["ticker"], name="stocks_stoc_ticker_5df4c9_idx"
            ),
        ),
    ]
