# Generated by Django 5.0.3 on 2024-04-09 18:28

from django.db import migrations
from django.db import models

import core.managers


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "unique": "A user with that username already exists."
                },
                max_length=254,
                unique=True,
                verbose_name="адрес электронной почты",
            ),
        ),
    ]
