# Generated by Django 5.0.3 on 2024-04-17 19:02

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["uuid"], name="core_user_uuid_f86e5b_idx"
            ),
        ),
    ]
