# Generated by Django 5.0.3 on 2024-05-20 14:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=4,
                default=10000,
                max_digits=12,
                verbose_name="баланс пользователя",
            ),
        ),
    ]
